//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Status_ttypes = require('./Status_types')
var Types_ttypes = require('./Types_types')


var ttypes = module.exports = {};
ttypes.TExecState = {
  'REGISTERED' : 0,
  'PLANNING' : 1,
  'QUEUED' : 2,
  'RUNNING' : 3,
  'FINISHED' : 4,
  'CANCELLED' : 5,
  'FAILED' : 6
};
TExecStats = module.exports.TExecStats = function(args) {
  this.latency_ns = null;
  this.cpu_time_ns = null;
  this.cardinality = null;
  this.memory_used = null;
  if (args) {
    if (args.latency_ns !== undefined && args.latency_ns !== null) {
      this.latency_ns = args.latency_ns;
    }
    if (args.cpu_time_ns !== undefined && args.cpu_time_ns !== null) {
      this.cpu_time_ns = args.cpu_time_ns;
    }
    if (args.cardinality !== undefined && args.cardinality !== null) {
      this.cardinality = args.cardinality;
    }
    if (args.memory_used !== undefined && args.memory_used !== null) {
      this.memory_used = args.memory_used;
    }
  }
};
TExecStats.prototype = {};
TExecStats.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.latency_ns = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.cpu_time_ns = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.cardinality = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.memory_used = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TExecStats.prototype.write = function(output) {
  output.writeStructBegin('TExecStats');
  if (this.latency_ns !== null && this.latency_ns !== undefined) {
    output.writeFieldBegin('latency_ns', Thrift.Type.I64, 1);
    output.writeI64(this.latency_ns);
    output.writeFieldEnd();
  }
  if (this.cpu_time_ns !== null && this.cpu_time_ns !== undefined) {
    output.writeFieldBegin('cpu_time_ns', Thrift.Type.I64, 2);
    output.writeI64(this.cpu_time_ns);
    output.writeFieldEnd();
  }
  if (this.cardinality !== null && this.cardinality !== undefined) {
    output.writeFieldBegin('cardinality', Thrift.Type.I64, 3);
    output.writeI64(this.cardinality);
    output.writeFieldEnd();
  }
  if (this.memory_used !== null && this.memory_used !== undefined) {
    output.writeFieldBegin('memory_used', Thrift.Type.I64, 4);
    output.writeI64(this.memory_used);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TPlanNodeExecSummary = module.exports.TPlanNodeExecSummary = function(args) {
  this.node_id = null;
  this.fragment_id = null;
  this.label = null;
  this.label_detail = null;
  this.num_children = null;
  this.estimated_stats = null;
  this.exec_stats = null;
  this.is_active = null;
  this.is_broadcast = null;
  if (args) {
    if (args.node_id !== undefined && args.node_id !== null) {
      this.node_id = args.node_id;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field node_id is unset!');
    }
    if (args.fragment_id !== undefined && args.fragment_id !== null) {
      this.fragment_id = args.fragment_id;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field fragment_id is unset!');
    }
    if (args.label !== undefined && args.label !== null) {
      this.label = args.label;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field label is unset!');
    }
    if (args.label_detail !== undefined && args.label_detail !== null) {
      this.label_detail = args.label_detail;
    }
    if (args.num_children !== undefined && args.num_children !== null) {
      this.num_children = args.num_children;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field num_children is unset!');
    }
    if (args.estimated_stats !== undefined && args.estimated_stats !== null) {
      this.estimated_stats = new ttypes.TExecStats(args.estimated_stats);
    }
    if (args.exec_stats !== undefined && args.exec_stats !== null) {
      this.exec_stats = Thrift.copyList(args.exec_stats, [ttypes.TExecStats]);
    }
    if (args.is_active !== undefined && args.is_active !== null) {
      this.is_active = Thrift.copyList(args.is_active, [null]);
    }
    if (args.is_broadcast !== undefined && args.is_broadcast !== null) {
      this.is_broadcast = args.is_broadcast;
    }
  }
};
TPlanNodeExecSummary.prototype = {};
TPlanNodeExecSummary.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.node_id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.fragment_id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.label = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.label_detail = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.num_children = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRUCT) {
        this.estimated_stats = new ttypes.TExecStats();
        this.estimated_stats.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.exec_stats = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.TExecStats();
          elem6.read(input);
          this.exec_stats.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.LIST) {
        var _size7 = 0;
        var _rtmp311;
        this.is_active = [];
        var _etype10 = 0;
        _rtmp311 = input.readListBegin();
        _etype10 = _rtmp311.etype;
        _size7 = _rtmp311.size;
        for (var _i12 = 0; _i12 < _size7; ++_i12)
        {
          var elem13 = null;
          elem13 = input.readBool();
          this.is_active.push(elem13);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.BOOL) {
        this.is_broadcast = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TPlanNodeExecSummary.prototype.write = function(output) {
  output.writeStructBegin('TPlanNodeExecSummary');
  if (this.node_id !== null && this.node_id !== undefined) {
    output.writeFieldBegin('node_id', Thrift.Type.I32, 1);
    output.writeI32(this.node_id);
    output.writeFieldEnd();
  }
  if (this.fragment_id !== null && this.fragment_id !== undefined) {
    output.writeFieldBegin('fragment_id', Thrift.Type.I32, 2);
    output.writeI32(this.fragment_id);
    output.writeFieldEnd();
  }
  if (this.label !== null && this.label !== undefined) {
    output.writeFieldBegin('label', Thrift.Type.STRING, 3);
    output.writeString(this.label);
    output.writeFieldEnd();
  }
  if (this.label_detail !== null && this.label_detail !== undefined) {
    output.writeFieldBegin('label_detail', Thrift.Type.STRING, 4);
    output.writeString(this.label_detail);
    output.writeFieldEnd();
  }
  if (this.num_children !== null && this.num_children !== undefined) {
    output.writeFieldBegin('num_children', Thrift.Type.I32, 5);
    output.writeI32(this.num_children);
    output.writeFieldEnd();
  }
  if (this.estimated_stats !== null && this.estimated_stats !== undefined) {
    output.writeFieldBegin('estimated_stats', Thrift.Type.STRUCT, 6);
    this.estimated_stats.write(output);
    output.writeFieldEnd();
  }
  if (this.exec_stats !== null && this.exec_stats !== undefined) {
    output.writeFieldBegin('exec_stats', Thrift.Type.LIST, 7);
    output.writeListBegin(Thrift.Type.STRUCT, this.exec_stats.length);
    for (var iter14 in this.exec_stats)
    {
      if (this.exec_stats.hasOwnProperty(iter14))
      {
        iter14 = this.exec_stats[iter14];
        iter14.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.is_active !== null && this.is_active !== undefined) {
    output.writeFieldBegin('is_active', Thrift.Type.LIST, 8);
    output.writeListBegin(Thrift.Type.BOOL, this.is_active.length);
    for (var iter15 in this.is_active)
    {
      if (this.is_active.hasOwnProperty(iter15))
      {
        iter15 = this.is_active[iter15];
        output.writeBool(iter15);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.is_broadcast !== null && this.is_broadcast !== undefined) {
    output.writeFieldBegin('is_broadcast', Thrift.Type.BOOL, 9);
    output.writeBool(this.is_broadcast);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TExecSummary = module.exports.TExecSummary = function(args) {
  this.state = null;
  this.status = null;
  this.nodes = null;
  this.exch_to_sender_map = null;
  this.error_logs = null;
  if (args) {
    if (args.state !== undefined && args.state !== null) {
      this.state = args.state;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field state is unset!');
    }
    if (args.status !== undefined && args.status !== null) {
      this.status = new Status_ttypes.TStatus(args.status);
    }
    if (args.nodes !== undefined && args.nodes !== null) {
      this.nodes = Thrift.copyList(args.nodes, [ttypes.TPlanNodeExecSummary]);
    }
    if (args.exch_to_sender_map !== undefined && args.exch_to_sender_map !== null) {
      this.exch_to_sender_map = Thrift.copyMap(args.exch_to_sender_map, [null]);
    }
    if (args.error_logs !== undefined && args.error_logs !== null) {
      this.error_logs = Thrift.copyList(args.error_logs, [null]);
    }
  }
};
TExecSummary.prototype = {};
TExecSummary.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.state = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.status = new Status_ttypes.TStatus();
        this.status.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.LIST) {
        var _size16 = 0;
        var _rtmp320;
        this.nodes = [];
        var _etype19 = 0;
        _rtmp320 = input.readListBegin();
        _etype19 = _rtmp320.etype;
        _size16 = _rtmp320.size;
        for (var _i21 = 0; _i21 < _size16; ++_i21)
        {
          var elem22 = null;
          elem22 = new ttypes.TPlanNodeExecSummary();
          elem22.read(input);
          this.nodes.push(elem22);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.MAP) {
        var _size23 = 0;
        var _rtmp327;
        this.exch_to_sender_map = {};
        var _ktype24 = 0;
        var _vtype25 = 0;
        _rtmp327 = input.readMapBegin();
        _ktype24 = _rtmp327.ktype;
        _vtype25 = _rtmp327.vtype;
        _size23 = _rtmp327.size;
        for (var _i28 = 0; _i28 < _size23; ++_i28)
        {
          var key29 = null;
          var val30 = null;
          key29 = input.readI32();
          val30 = input.readI32();
          this.exch_to_sender_map[key29] = val30;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.LIST) {
        var _size31 = 0;
        var _rtmp335;
        this.error_logs = [];
        var _etype34 = 0;
        _rtmp335 = input.readListBegin();
        _etype34 = _rtmp335.etype;
        _size31 = _rtmp335.size;
        for (var _i36 = 0; _i36 < _size31; ++_i36)
        {
          var elem37 = null;
          elem37 = input.readString();
          this.error_logs.push(elem37);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TExecSummary.prototype.write = function(output) {
  output.writeStructBegin('TExecSummary');
  if (this.state !== null && this.state !== undefined) {
    output.writeFieldBegin('state', Thrift.Type.I32, 1);
    output.writeI32(this.state);
    output.writeFieldEnd();
  }
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.STRUCT, 2);
    this.status.write(output);
    output.writeFieldEnd();
  }
  if (this.nodes !== null && this.nodes !== undefined) {
    output.writeFieldBegin('nodes', Thrift.Type.LIST, 3);
    output.writeListBegin(Thrift.Type.STRUCT, this.nodes.length);
    for (var iter38 in this.nodes)
    {
      if (this.nodes.hasOwnProperty(iter38))
      {
        iter38 = this.nodes[iter38];
        iter38.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.exch_to_sender_map !== null && this.exch_to_sender_map !== undefined) {
    output.writeFieldBegin('exch_to_sender_map', Thrift.Type.MAP, 4);
    output.writeMapBegin(Thrift.Type.I32, Thrift.Type.I32, Thrift.objectLength(this.exch_to_sender_map));
    for (var kiter39 in this.exch_to_sender_map)
    {
      if (this.exch_to_sender_map.hasOwnProperty(kiter39))
      {
        var viter40 = this.exch_to_sender_map[kiter39];
        output.writeI32(kiter39);
        output.writeI32(viter40);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.error_logs !== null && this.error_logs !== undefined) {
    output.writeFieldBegin('error_logs', Thrift.Type.LIST, 5);
    output.writeListBegin(Thrift.Type.STRING, this.error_logs.length);
    for (var iter41 in this.error_logs)
    {
      if (this.error_logs.hasOwnProperty(iter41))
      {
        iter41 = this.error_logs[iter41];
        output.writeString(iter41);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

