//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var ExecStats_ttypes = require('./ExecStats_types')
var Status_ttypes = require('./Status_types')
var Types_ttypes = require('./Types_types')
var beeswax_ttypes = require('./beeswax_types')
var TCLIService_ttypes = require('./TCLIService_types')


var TCLIService = require('./TCLIService')
var TCLIServiceClient = TCLIService.Client
var TCLIServiceProcessor = TCLIService.Processor
var ttypes = require('./ImpalaService_types');
//HELPER FUNCTIONS AND STRUCTURES

ImpalaHiveServer2Service_GetExecSummary_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined && args.req !== null) {
      this.req = new ttypes.TGetExecSummaryReq(args.req);
    }
  }
};
ImpalaHiveServer2Service_GetExecSummary_args.prototype = {};
ImpalaHiveServer2Service_GetExecSummary_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new ttypes.TGetExecSummaryReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImpalaHiveServer2Service_GetExecSummary_args.prototype.write = function(output) {
  output.writeStructBegin('ImpalaHiveServer2Service_GetExecSummary_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImpalaHiveServer2Service_GetExecSummary_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.TGetExecSummaryResp(args.success);
    }
  }
};
ImpalaHiveServer2Service_GetExecSummary_result.prototype = {};
ImpalaHiveServer2Service_GetExecSummary_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.TGetExecSummaryResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImpalaHiveServer2Service_GetExecSummary_result.prototype.write = function(output) {
  output.writeStructBegin('ImpalaHiveServer2Service_GetExecSummary_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImpalaHiveServer2Service_GetRuntimeProfile_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined && args.req !== null) {
      this.req = new ttypes.TGetRuntimeProfileReq(args.req);
    }
  }
};
ImpalaHiveServer2Service_GetRuntimeProfile_args.prototype = {};
ImpalaHiveServer2Service_GetRuntimeProfile_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new ttypes.TGetRuntimeProfileReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImpalaHiveServer2Service_GetRuntimeProfile_args.prototype.write = function(output) {
  output.writeStructBegin('ImpalaHiveServer2Service_GetRuntimeProfile_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImpalaHiveServer2Service_GetRuntimeProfile_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.TGetRuntimeProfileResp(args.success);
    }
  }
};
ImpalaHiveServer2Service_GetRuntimeProfile_result.prototype = {};
ImpalaHiveServer2Service_GetRuntimeProfile_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.TGetRuntimeProfileResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ImpalaHiveServer2Service_GetRuntimeProfile_result.prototype.write = function(output) {
  output.writeStructBegin('ImpalaHiveServer2Service_GetRuntimeProfile_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ImpalaHiveServer2ServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
Thrift.inherits(ImpalaHiveServer2ServiceClient, TCLIServiceClient);
ImpalaHiveServer2ServiceClient.prototype.seqid = function() { return this._seqid; }
ImpalaHiveServer2ServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
ImpalaHiveServer2ServiceClient.prototype.GetExecSummary = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetExecSummary(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetExecSummary(req);
  }
};

ImpalaHiveServer2ServiceClient.prototype.send_GetExecSummary = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetExecSummary', Thrift.MessageType.CALL, this.seqid());
  var args = new ImpalaHiveServer2Service_GetExecSummary_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ImpalaHiveServer2ServiceClient.prototype.recv_GetExecSummary = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ImpalaHiveServer2Service_GetExecSummary_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetExecSummary failed: unknown result');
};
ImpalaHiveServer2ServiceClient.prototype.GetRuntimeProfile = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetRuntimeProfile(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetRuntimeProfile(req);
  }
};

ImpalaHiveServer2ServiceClient.prototype.send_GetRuntimeProfile = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetRuntimeProfile', Thrift.MessageType.CALL, this.seqid());
  var args = new ImpalaHiveServer2Service_GetRuntimeProfile_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ImpalaHiveServer2ServiceClient.prototype.recv_GetRuntimeProfile = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ImpalaHiveServer2Service_GetRuntimeProfile_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetRuntimeProfile failed: unknown result');
};
ImpalaHiveServer2ServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
Thrift.inherits(ImpalaHiveServer2ServiceProcessor, TCLIServiceProcessor)
ImpalaHiveServer2ServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ImpalaHiveServer2ServiceProcessor.prototype.process_GetExecSummary = function(seqid, input, output) {
  var args = new ImpalaHiveServer2Service_GetExecSummary_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetExecSummary.length === 1) {
    Q.fcall(this._handler.GetExecSummary, args.req)
      .then(function(result) {
        var result = new ImpalaHiveServer2Service_GetExecSummary_result({success: result});
        output.writeMessageBegin("GetExecSummary", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetExecSummary", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.GetExecSummary(args.req, function (err, result) {
      if (err == null) {
        var result = new ImpalaHiveServer2Service_GetExecSummary_result((err != null ? err : {success: result}));
        output.writeMessageBegin("GetExecSummary", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetExecSummary", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

ImpalaHiveServer2ServiceProcessor.prototype.process_GetRuntimeProfile = function(seqid, input, output) {
  var args = new ImpalaHiveServer2Service_GetRuntimeProfile_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetRuntimeProfile.length === 1) {
    Q.fcall(this._handler.GetRuntimeProfile, args.req)
      .then(function(result) {
        var result = new ImpalaHiveServer2Service_GetRuntimeProfile_result({success: result});
        output.writeMessageBegin("GetRuntimeProfile", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetRuntimeProfile", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.GetRuntimeProfile(args.req, function (err, result) {
      if (err == null) {
        var result = new ImpalaHiveServer2Service_GetRuntimeProfile_result((err != null ? err : {success: result}));
        output.writeMessageBegin("GetRuntimeProfile", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetRuntimeProfile", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

